# Generated by Django 4.1 on 2022-08-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.CharField(max_length=100, verbose_name='Значения')),
                ('filials', models.CharField(max_length=100, verbose_name='Количество филиалов')),
                ('startapps', models.CharField(max_length=100, verbose_name='Стартап-Проектов')),
                ('volume', models.CharField(max_length=100, verbose_name='Объем')),
                ('incubation', models.CharField(max_length=100, verbose_name='Инкубацинные центры')),
                ('trained', models.CharField(max_length=100, verbose_name='Обучено госслужащих')),
                ('events', models.CharField(max_length=100, verbose_name='Количество мероприятий')),
                ('partners', models.CharField(max_length=100, verbose_name='Количество партнеров')),
                ('participants', models.CharField(max_length=100, verbose_name='Количество участников конкурсов')),
                ('staff', models.CharField(max_length=100, verbose_name='Сотрудников IT Park')),
            ],
            options={
                'verbose_name': 'Значения Dashboard',
                'verbose_name_plural': 'Значение Dashboard',
            },
        ),
    ]
