# Generated by Django 4.1 on 2022-08-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itpark',
            options={'verbose_name': 'Значение Dashboard', 'verbose_name_plural': 'Значения Dashboard'},
        ),
    ]
